<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />


<?=$this->getIcons()?>

<meta http-equiv="content-type" content="text/html; charset=<?=$this->getEncoding()?>" />
<meta name="description" content="" />

<title><?=$this->getTitle()?></title>
	<?=$this->getScripts()?>
	<?=$this->getStyles()?>
</head>
<body>
<h1>test:::<?=$this->test1?></h1>
</body>
</html>